#!/bin/sh
# Build supabase/.env for the local edge runtime from .env.local.prod
# (single secrets file — no separate supabase/.env.local copy step).
#
# Optional override: if supabase/.env.local exists, it is appended last and wins.
set -eu
cd "$(dirname "$0")/.."

if [ ! -f .env.local.prod ]; then
  echo "missing .env.local.prod" >&2
  exit 1
fi

# Keys the local edge functions read (see supabase/functions/**).
EDGE_KEYS="
ADMIN_ALLOWED_EMAILS
RESEND_API_KEY
RESEND_FROM_EMAIL
RESEND_LOGO_URL
DISCORD_WEBHOOK_URL
CARD_TIMER_DISCORD_WEBHOOK_URL
SHEETS_WEBHOOK_URL
SHEETS_SECRET
SHEET_VIEW_URL
ORDERS_SHEETS_WEBHOOK_URL
ORDERS_SHEETS_SECRET
ORDERS_SHEET_VIEW_URL
POKEMON_TCG_API_KEY
"

tmp="$(mktemp)"
{
  echo "# Generated by scripts/sync-local-edge-env.sh — do not edit."
  echo "# Source: .env.local.prod (+ optional supabase/.env.local overrides)."
  echo ""

  for key in $EDGE_KEYS; do
    line="$(grep -E "^${key}=" .env.local.prod 2>/dev/null | tail -n 1 || true)"
    if [ -n "$line" ]; then
      echo "$line"
    fi
  done

  # Mirror public admin allowlist into the server secret if unset.
  if ! grep -q '^ADMIN_ALLOWED_EMAILS=' .env.local.prod 2>/dev/null; then
    pub="$(grep -E '^NEXT_PUBLIC_ADMIN_ALLOWED_EMAILS=' .env.local.prod 2>/dev/null | tail -n 1 || true)"
    if [ -n "$pub" ]; then
      echo "$pub" | sed 's/^NEXT_PUBLIC_ADMIN_ALLOWED_EMAILS=/ADMIN_ALLOWED_EMAILS=/'
    fi
  fi

  if [ -f supabase/.env.local ]; then
    echo ""
    echo "# --- overrides from supabase/.env.local ---"
    grep -E '^[A-Za-z_][A-Za-z0-9_]*=' supabase/.env.local || true
  fi
} >"$tmp"

mkdir -p supabase
mv "$tmp" supabase/.env

if ! grep -qE '^DISCORD_WEBHOOK_URL=.+' supabase/.env 2>/dev/null; then
  echo "note: DISCORD_WEBHOOK_URL not set in .env.local.prod — local order notify won't post to Discord"
fi
if ! grep -qE '^ADMIN_ALLOWED_EMAILS=.+' supabase/.env 2>/dev/null; then
  echo "note: ADMIN_ALLOWED_EMAILS not set — local /admin login gate will reject everyone"
fi

echo "supabase/.env <- synced from .env.local.prod"
