-- PokePatch database schema (reference documentation)
--
-- Apply changes via migrations in supabase/migrations/, or paste a migration
-- into the Supabase SQL Editor.
--
-- SAFETY: migrations must be additive only. Never DROP/ALTER/TRUNCATE
-- quote_requests — it holds historical submissions and the legacy notify path.

-- ---------------------------------------------------------------------------
-- Legacy: quote_requests (kept for historical data + legacy notify webhook)
-- ---------------------------------------------------------------------------
--
-- create table public.quote_requests (
--   id bigint generated always as identity primary key,
--   created_at timestamptz not null default now(),
--   delivery_method text not null check (delivery_method in ('local_dropoff', 'shipping')),
--   restoration_details text not null,
--   contact text not null,
--   image_paths text[] not null default '{}'
-- );
--
-- RLS: anon INSERT only.
-- Webhook: INSERT → notify edge function (legacy path).

-- ---------------------------------------------------------------------------
-- Orders (working + original backup)
-- ---------------------------------------------------------------------------
--
-- See: supabase/migrations/20260704000000_orders_schema.sql
--
-- Working tables (admin edits these):
--   orders, contacts, cards, card_images
--   orders.queue_priority — lower = higher priority among open orders
--   orders.photos_drive_url — optional Google Drive folder URL for the order
--
-- Original backup (written once by create_order, never updated):
--   orders_original, contacts_original, cards_original, card_images_original
--
-- RPCs:
--   create_order(p_payload jsonb)  — public form; EXECUTE granted to anon
--   update_order(...)              — admin only; EXECUTE granted to service_role
--                                   (when p_cards provided, omitted cards are deleted)
--   get_queue_card_count()         — public; { todo, in_progress, completed };
--                                   todo = cards.status todo on orders new|on_hold
--   orders.queue_priority          — relative rank within status (0..n-1 per column)
--   get_my_orders.queue_position   — 1-based place among status=new
--   reorder_status_orders(status, ids[]) / move_order_in_status(...) — service_role; kanban
--
-- Webhook: orders INSERT → notify edge function (new path).
--
-- Storage paths: card-photos/order-{orderUuid}/card-{cardUuid}/customer-{n}-...

-- ---------------------------------------------------------------------------
-- Gallery (public marketing restorations, managed via /admin/)
-- ---------------------------------------------------------------------------
--
-- See: supabase/migrations/20260714000000_gallery_items.sql
--      (+ pairs, set_name, damage_tags, drop item sort_order through 20260714040000)
--      (+ gallery_items_published_created_at_idx in 20260716000000)
--
-- Table: gallery_items (title, set_name, damage_tags, published; ordered by created_at desc)
-- Index: gallery_items_published_created_at_idx (published, created_at desc)
-- Table: gallery_pairs (before/after storage paths per item; ordered list)
-- Bucket: gallery (public)
-- RLS: anon SELECT published items + their pairs
-- Writes: admin-api edge function (service role)
-- Seed existing public/gallery assets:
--   node --env-file=.env.local scripts/seed-gallery.mjs
-- ---------------------------------------------------------------------------
-- Storage policies (run in SQL Editor if not already configured)
-- ---------------------------------------------------------------------------
--
-- Bucket: card-photos (create in Dashboard if missing; public or private is fine
-- because notify uses signed URLs via the service role).
--
-- Allow anon to upload under order-* paths (new form) and legacy uuid folders:
--
-- insert into storage.buckets (id, name, public)
-- values ('card-photos', 'card-photos', false)
-- on conflict (id) do nothing;
--
-- create policy "anon can upload card photos"
--   on storage.objects for insert to anon
--   with check (bucket_id = 'card-photos');
--
-- (Tighten to path prefixes if desired, e.g. name like 'order-%' or legacy uuid.)
--
-- Bucket: gallery (public marketing media for /gallery page)
-- insert into storage.buckets (id, name, public)
-- values ('gallery', 'gallery', true)
-- on conflict (id) do nothing;